# PR 자동 라벨링 설정
# 변경된 파일 경로에 따라 라벨을 자동으로 추가합니다.

# 카테고리 라벨
"category: docs":
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "*.md"
          - "!workflows/**/*"
          - "!examples/**/*"
          - "!templates/**/*"

"category: workflow":
  - changed-files:
      - any-glob-to-any-file:
          - "workflows/**/*"

"category: example":
  - changed-files:
      - any-glob-to-any-file:
          - "examples/**/*"

"category: template":
  - changed-files:
      - any-glob-to-any-file:
          - "templates/**/*"

# 영역 라벨
"area: hooks":
  - changed-files:
      - any-glob-to-any-file:
          - "examples/hooks/**/*"

"area: mcp":
  - changed-files:
      - any-glob-to-any-file:
          - "examples/mcp/**/*"

"area: prompts":
  - changed-files:
      - any-glob-to-any-file:
          - "examples/prompts/**/*"

"area: code-review":
  - changed-files:
      - any-glob-to-any-file:
          - "workflows/code-review.md"

"area: debugging":
  - changed-files:
      - any-glob-to-any-file:
          - "workflows/debugging.md"

"area: refactoring":
  - changed-files:
      - any-glob-to-any-file:
          - "workflows/refactoring.md"

# GitHub 설정
"area: github-actions":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"
